spring:
  application:
    name: eureka-service
  boot:
    admin:
      client:
        url:
        - http://localhost:8084

server:
  port: 8761
  
eureka:
  client:
    registerWithEureka: false #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0  #wait time for subsequent sync